# Generated by Django 4.0.3 on 2022-04-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_remove_site_sslcertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteID', models.IntegerField()),
                ('responseTime', models.FloatField()),
            ],
        ),
    ]
