# Generated by Django 4.0.3 on 2022-04-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_responsetimes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponseTimes',
            new_name='ResponseTime',
        ),
    ]
