# Generated by Django 4.0.4 on 2022-04-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_rename_responsetimes_responsetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetime',
            name='timeRecorded',
            field=models.DateTimeField(null=True),
        ),
    ]
