# Generated by Django 4.0.4 on 2022-05-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_responsetime_timerecorded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseTime',
        ),
    ]
